### ISSUE TITLE
Bombs being duplicated.

### ISSUE THREAD

**Issue by ericnkatz** [mgingras/fBomb#1]
The same "bomb" is coming into the feed more than once.

**Comment by mgingras** [comment]
@ericnkatz, Hey, do you have any examples of this? I cannot replicate it.

**Comment by ericnkatz** [comment]
I run into this, where it just streams the same tweet more than once. 

![i5j3vll-f_x2djzpnjpc7adftm1jdfwiyyywdcw210k](https://cloud.githubusercontent.com/assets/91019/3168207/f925819a-eb7b-11e3-973e-116ffe3e5a14.png)

**Comment by mgingras** [comment]
Interesting, what browser is that on?

**Comment by ericnkatz** [comment]
Chrome. Version 35.0.1916.114

**Comment by ericnkatz** [comment]
It is even more noticeable when using tracking words that aren't very popular such as:

```
{ "track": "baby boy,baby girl,baby shower,baby gift,babyshower" }
```

![screenshot 2014-06-03 20 15 47](https://cloud.githubusercontent.com/assets/91019/3168282/6d0055e4-eb7d-11e3-9c75-a9584f1f18d8.png)

**Comment by mgingras** [comment]
Con not reproduce issue. Will close and re-open if it re-appears.
